# See help here: https://github.com/marketplace/actions/labeler

TEST:
  - "tests/**/*"
DOC:
  - "docs/**/*"
  - "**/*.md"
  - "LICENSE"
  - "third-party-programs.txt"
  - "NOTICE"
  - "for_developers/**/*"
BUILD:
  - ".ci/**/*"
  - ".github/**/*"
  - ".pre-commit-config.yaml"
  - "markdownlint.rb"
  - "pyproject.toml"
  - "tox.ini"
  - "MANIFEST.in"
DEPENDENCY:
  - "requirements/*"
  - "pyproject.toml"
